// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

var List                 = require("bs-platform/lib/js/list.js");
var $$Array              = require("bs-platform/lib/js/array.js");
var Block                = require("bs-platform/lib/js/block.js");
var Curry                = require("bs-platform/lib/js/curry.js");
var ImageRe              = require("bs-react-native/lib/js/src/components/imageRe.js");
var StyleRe              = require("bs-react-native/lib/js/src/styleRe.js");
var AnimatedRe           = require("bs-react-native/lib/js/src/animatedRe.js");
var Pervasives           = require("bs-platform/lib/js/pervasives.js");
var PlatformRe           = require("bs-react-native/lib/js/src/platformRe.js");
var ReactNative          = require("bs-react-native/lib/js/src/reactNative.js");
var ReasonReact          = require("reason-react/lib/js/src/reasonReact.js");
var StyleSheetRe         = require("bs-react-native/lib/js/src/styleSheetRe.js");
var TouchableOpacityRe   = require("bs-react-native/lib/js/src/components/touchableOpacityRe.js");
var AnimatedComponentsRe = require("bs-react-native/lib/js/src/components/animatedComponentsRe.js");

function getPlatformStyle(iosSize, androidSize) {
  if (PlatformRe.os !== 0) {
    return androidSize;
  } else {
    return iosSize;
  }
}

var appBarHeight = PlatformRe.os !== 0 ? 56 : 44;

var statusBarHeight = PlatformRe.os !== 0 ? 0 : 20;

var titleOffset = PlatformRe.os !== 0 ? 56 : 70;

var iosPlatformStyle_000 = StyleRe.borderBottomWidth(StyleSheetRe.hairlineWidth);

var iosPlatformStyle_001 = /* :: */[
  StyleRe.borderBottomColor("rgba(0, 0, 0, .3)"),
  /* [] */0
];

var iosPlatformStyle = /* :: */[
  iosPlatformStyle_000,
  iosPlatformStyle_001
];

var androidPlatformStyle_000 = StyleRe.shadowColor("black");

var androidPlatformStyle_001 = /* :: */[
  StyleRe.shadowOpacity(0.1),
  /* :: */[
    StyleRe.shadowRadius(StyleSheetRe.hairlineWidth),
    /* :: */[
      StyleRe.elevation(4),
      /* [] */0
    ]
  ]
];

var androidPlatformStyle = /* :: */[
  androidPlatformStyle_000,
  androidPlatformStyle_001
];

var platformContainerStyles = getPlatformStyle(iosPlatformStyle, androidPlatformStyle);

var shared_000 = StyleRe.justifyContent(/* center */98248149);

var shared_001 = /* :: */[
  StyleRe.alignItems(/* center */98248149),
  /* :: */[
    StyleRe.backgroundColor("transparent"),
    /* [] */0
  ]
];

var shared = /* :: */[
  shared_000,
  shared_001
];

var styles = StyleSheetRe.create({
      right: StyleRe.style(/* :: */[
            StyleRe.right(0),
            /* :: */[
              StyleRe.bottom(0),
              /* :: */[
                StyleRe.top(0),
                /* :: */[
                  StyleRe.position(/* absolute */-1013592457),
                  /* [] */0
                ]
              ]
            ]
          ])
    });

var ItemStyle = /* module */[
  /* shared */shared,
  /* styles */styles
];

function computedStyle(position, index) {
  var index$1 = index;
  return StyleRe.style(/* :: */[
              StyleRe.opacityInterpolated(AnimatedRe.Value[/* interpolate */10](position, /* :: */[
                        index$1 - 1,
                        /* :: */[
                          index$1,
                          /* :: */[
                            index$1 + 1,
                            /* [] */0
                          ]
                        ]
                      ], /* `float */[
                        43435420,
                        /* :: */[
                          0,
                          /* :: */[
                            1,
                            /* :: */[
                              0,
                              /* [] */0
                            ]
                          ]
                        ]
                      ], /* None */0, /* None */0, /* None */0, /* None */0, /* () */0)),
              /* :: */[
                StyleRe.transformInterpolated(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[AnimatedRe.Value[/* interpolate */10](position, /* :: */[
                            index$1 - 1,
                            /* :: */[
                              index$1 + 1,
                              /* [] */0
                            ]
                          ], /* `float */[
                            43435420,
                            /* :: */[
                              200,
                              /* :: */[
                                -200,
                                /* [] */0
                              ]
                            ]
                          ], /* None */0, /* None */0, /* None */0, /* None */0, /* () */0)], /* None */0, /* None */0, /* None */0, /* () */0),
                /* [] */0
              ]
            ]);
}

var styles$1 = StyleSheetRe.create({
      titleContainer: StyleRe.style(/* :: */[
            StyleRe.bottom(0),
            /* :: */[
              StyleRe.left(titleOffset),
              /* :: */[
                StyleRe.right(titleOffset),
                /* :: */[
                  StyleRe.top(0),
                  /* :: */[
                    StyleRe.position(/* absolute */-1013592457),
                    /* :: */[
                      StyleRe.alignItems(PlatformRe.os !== 0 ? /* flexStart */662439529 : /* center */98248149),
                      shared
                    ]
                  ]
                ]
              ]
            ]
          ]),
      title: StyleRe.style(/* :: */[
            StyleRe.fontSize(PlatformRe.os !== 0 ? 20.0 : 17.0),
            /* :: */[
              StyleRe.fontWeight(PlatformRe.os !== 0 ? /* _500 */1056155254 : /* _600 */1056204983),
              /* :: */[
                StyleRe.color("rgba(0, 0, 0, .9)"),
                /* :: */[
                  StyleRe.textAlign(PlatformRe.os !== 0 ? /* left */-944764921 : /* center */98248149),
                  /* :: */[
                    StyleRe.marginHorizontal(16),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ])
    });

function render(title, position, index) {
  var computed = computedStyle(position, index);
  var eta = Curry.app(AnimatedComponentsRe.Text[/* make */0], [
        /* None */0,
        /* None */0,
        /* None */0,
        /* Some */[1],
        /* None */0,
        /* None */0,
        /* None */0,
        /* None */0,
        /* None */0,
        /* Some */[styles$1.title],
        /* None */0,
        /* None */0,
        /* None */0,
        /* None */0,
        /* None */0,
        /* None */0,
        /* Some */[title],
        /* array */[]
      ]);
  return ReasonReact.element(/* None */0, /* None */0, Curry.app(AnimatedComponentsRe.View[/* make */0], [
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* Some */[StyleRe.concat(/* :: */[
                          computed,
                          /* :: */[
                            styles$1.titleContainer,
                            /* [] */0
                          ]
                        ])],
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* array */[ReasonReact.element(/* None */0, /* None */0, eta)]
                ]));
}

var IOS = /* module */[/* render */render];

function render$1(title) {
  var eta = Curry.app(AnimatedComponentsRe.Text[/* make */0], [
        /* None */0,
        /* None */0,
        /* None */0,
        /* Some */[1],
        /* None */0,
        /* None */0,
        /* None */0,
        /* None */0,
        /* None */0,
        /* Some */[styles$1.title],
        /* None */0,
        /* None */0,
        /* None */0,
        /* None */0,
        /* None */0,
        /* None */0,
        /* Some */[title],
        /* array */[]
      ]);
  return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* Some */[styles$1.titleContainer],
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* array */[ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* Some */[styles$1.titleContainer],
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* array */[ReasonReact.element(/* None */0, /* None */0, eta)]
                            ]))]
                ]));
}

var Android = /* module */[/* render */render$1];

var HeaderTitle = /* module */[
  /* computedStyle */computedStyle,
  /* styles */styles$1,
  /* IOS */IOS,
  /* Android */Android
];

function computedStyle$1(position, index) {
  var index$1 = index;
  return StyleRe.style(/* :: */[
              StyleRe.opacityInterpolated(AnimatedRe.Value[/* interpolate */10](position, /* :: */[
                        index$1 - 1,
                        /* :: */[
                          index$1 - 0.5,
                          /* :: */[
                            index$1,
                            /* :: */[
                              index$1 + 0.5,
                              /* :: */[
                                index$1 + 1,
                                /* [] */0
                              ]
                            ]
                          ]
                        ]
                      ], /* `float */[
                        43435420,
                        /* :: */[
                          0,
                          /* :: */[
                            0,
                            /* :: */[
                              1,
                              /* :: */[
                                0,
                                /* :: */[
                                  0,
                                  /* [] */0
                                ]
                              ]
                            ]
                          ]
                        ]
                      ], /* None */0, /* None */0, /* None */0, /* None */0, /* () */0)),
              /* [] */0
            ]);
}

var iconIOS_000 = StyleRe.height(21);

var iconIOS_001 = /* :: */[
  StyleRe.width(13),
  /* :: */[
    StyleRe.marginLeft(10),
    /* :: */[
      StyleRe.marginRight(22),
      /* :: */[
        StyleRe.marginVertical(12),
        /* :: */[
          StyleRe.resizeMode(/* contain */427065300),
          /* [] */0
        ]
      ]
    ]
  ]
];

var iconIOS = /* :: */[
  iconIOS_000,
  iconIOS_001
];

var iconAndroid_000 = StyleRe.height(24);

var iconAndroid_001 = /* :: */[
  StyleRe.width(24),
  /* :: */[
    StyleRe.margin(16),
    /* :: */[
      StyleRe.resizeMode(/* contain */427065300),
      /* [] */0
    ]
  ]
];

var iconAndroid = /* :: */[
  iconAndroid_000,
  iconAndroid_001
];

var styles$2 = StyleSheetRe.create({
      container: StyleRe.style(/* :: */[
            StyleRe.alignItems(/* center */98248149),
            /* :: */[
              StyleRe.flexDirection(/* row */5693978),
              /* :: */[
                StyleRe.backgroundColor("transparent"),
                /* [] */0
              ]
            ]
          ]),
      iconWithTitle: getPlatformStyle(StyleRe.style(/* :: */[
                StyleRe.marginRight(5),
                /* [] */0
              ]), StyleRe.style(/* [] */0)),
      icon: StyleRe.style(getPlatformStyle(iconIOS, iconAndroid)),
      containerLeft: StyleRe.style(Pervasives.$at(shared, /* :: */[
                StyleRe.left(0),
                /* :: */[
                  StyleRe.bottom(0),
                  /* :: */[
                    StyleRe.top(0),
                    /* :: */[
                      StyleRe.position(/* absolute */-1013592457),
                      /* [] */0
                    ]
                  ]
                ]
              ]))
    });

function backButtonText() {
  return null;
}

function render$2(position, index, onPress) {
  var style = computedStyle$1(position, index);
  return ReasonReact.element(/* None */0, /* None */0, Curry.app(AnimatedComponentsRe.View[/* make */0], [
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* Some */[StyleRe.concat(/* :: */[
                          style,
                          /* :: */[
                            styles$2.containerLeft,
                            /* [] */0
                          ]
                        ])],
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* array */[ReasonReact.element(/* None */0, /* None */0, TouchableOpacityRe.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[styles$2.container], /* None */0, /* Some */[onPress], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* Some */[styles$2.container],
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* None */0,
                                        /* array */[
                                          ReasonReact.element(/* None */0, /* None */0, ImageRe.Image[/* make */3](/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* Required */Block.__(1, [require("../../../assets/back.png")])], /* Some */[styles$2.icon], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[])),
                                          null
                                        ]
                                      ]))]))]
                ]));
}

var HeaderBackButton = /* module */[
  /* computedStyle */computedStyle$1,
  /* iconIOS */iconIOS,
  /* iconAndroid */iconAndroid,
  /* styles */styles$2,
  /* backButtonText */backButtonText,
  /* render */render$2
];

var styles$3 = StyleSheetRe.create({
      header2: StyleRe.style(/* :: */[
            StyleRe.flexDirection(/* row */5693978),
            /* [] */0
          ]),
      header1: StyleRe.style(/* :: */[
            StyleRe.flex(1),
            /* [] */0
          ]),
      header0: StyleRe.style(/* :: */[
            StyleRe.paddingTop(statusBarHeight),
            /* :: */[
              StyleRe.backgroundColor(PlatformRe.os !== 0 ? "#FFF" : "#F7F7F7"),
              /* :: */[
                StyleRe.height(statusBarHeight + appBarHeight),
                platformContainerStyles
              ]
            ]
          ])
    });

function renderHeader(goBack, position, index, title) {
  return ReasonReact.element(/* Some */[Pervasives.string_of_int(index) + title], /* None */0, Curry.app(ReactNative.View[/* make */0], [
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* Some */[StyleRe.concat(/* :: */[
                          StyleSheetRe.absoluteFill,
                          /* :: */[
                            styles$3.header2,
                            /* [] */0
                          ]
                        ])],
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* array */[
                    render(title, position, index),
                    index > 0 && PlatformRe.os !== /* Android */1 ? render$2(position, index, goBack) : null
                  ]
                ]));
}

function renderHeader$1(goBack, position, index, title) {
  return ReasonReact.element(/* Some */[Pervasives.string_of_int(index) + title], /* None */0, Curry.app(ReactNative.View[/* make */0], [
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* Some */[StyleRe.concat(/* :: */[
                          StyleSheetRe.absoluteFill,
                          /* :: */[
                            styles$3.header2,
                            /* [] */0
                          ]
                        ])],
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* array */[
                    render(title, position, index),
                    index > 0 ? render$2(position, index, goBack) : null
                  ]
                ]));
}

function renderHeadersIOS(goBack, titles, position) {
  return $$Array.of_list(List.mapi((function (param, param$1) {
                    return renderHeader$1(goBack, position, param, param$1);
                  }), titles));
}

function render$3(position, titles, goBack) {
  return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* Some */[styles$3.header0],
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* array */[ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* Some */[styles$3.header1],
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* array */[renderHeadersIOS(goBack, titles, position)]
                            ]))]
                ]));
}

var IOS$1 = /* module */[
  /* renderHeader */renderHeader$1,
  /* renderHeadersIOS */renderHeadersIOS,
  /* render */render$3
];

function renderHeader$2(title) {
  return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* Some */[StyleRe.concat(/* :: */[
                          StyleSheetRe.absoluteFill,
                          /* :: */[
                            styles$3.header2,
                            /* [] */0
                          ]
                        ])],
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* array */[render$1(title)]
                ]));
}

function render$4(title) {
  return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* Some */[styles$3.header0],
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* array */[ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* Some */[styles$3.header1],
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* array */[renderHeader$2(title)]
                            ]))]
                ]));
}

var Android$1 = /* module */[
  /* renderHeader */renderHeader$2,
  /* render */render$4
];

exports.getPlatformStyle        = getPlatformStyle;
exports.appBarHeight            = appBarHeight;
exports.statusBarHeight         = statusBarHeight;
exports.titleOffset             = titleOffset;
exports.iosPlatformStyle        = iosPlatformStyle;
exports.androidPlatformStyle    = androidPlatformStyle;
exports.platformContainerStyles = platformContainerStyles;
exports.ItemStyle               = ItemStyle;
exports.HeaderTitle             = HeaderTitle;
exports.HeaderBackButton        = HeaderBackButton;
exports.styles                  = styles$3;
exports.renderHeader            = renderHeader;
exports.IOS                     = IOS$1;
exports.Android                 = Android$1;
/* iosPlatformStyle Not a pure module */
